.PHONY: pre-commit/run pre-commit/all

## Run all pre-commit hooks
pre-commit/all:
	pre-commit run --all-files

## Run pre-commit hooks for staged files
pre-commit/run:
	pre-commit run --hook-stage pre-push